typography_spectrum: 0.2440025362297708
color:
  brandStrength: 0.7290653796352925
  lightness: 0.23219586384851523
  saturation: 0.6080751003490041
  rhythmicContrast: 0.10419920766818347
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
github: true
layout_spectrum: 0.12306166329255125
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39cc04cc-792e-40d9-b168-12e2617abcdc.png
name: Test Environment Manager
navigation:
  - name: Reasons
    id: f62428d4-d75c-4081-bd83-614335189ae2
    type: content
  - name: Agile
    id: f3d8ae96-73e5-4465-a2f9-90eaf5ca7c03
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fb01252c-6cae-4ecc-aca7-dffd45975915.png
title: Test Environment Manager
content: []
description: 'Applications and Test Environment Management in JIRA '
purpose:
  - type: external
    url: >-
      https://marketplace.atlassian.com/plugins/com.holydev.env.plugin.jira-holydev-env-plugin/server/overview
    label: TRY IT
  - type: contact
    url: 'mailto:contact@holydev.net'
    label: Contact us
